### ISSUE TITLE
Some WBPaper metadata missing from C. elegans site

### ISSUE THREAD

**Issue by vanaukenk** [TextpressoDevelopers/textpressocentral#33]
It looks like some papers, in particular those of type 'Book', are missing their metadata in TPC:

![image](https://user-images.githubusercontent.com/1730534/104376986-c727ea00-54f3-11eb-84e8-5963556c78cb.png)

There is metadata for these papers in postgres on tazendra, so I'm not sure what happens to it when the paper gets loaded into TPC.

**Comment by goldturtle** [comment]
It's fixed and should show up corrected at the website next week.

Michael.

**Comment by vanaukenk** [comment]
Thank you @goldturtle !
I'll check on the website next week and will close this ticket if all looks good.

**Comment by vanaukenk** [comment]
Looks okay now.  Thx @goldturtle
