### ISSUE TITLE
Bug: TPC runs search again (without set parameters) when expanding a paper result's details

### ISSUE THREAD

**Issue by chris-grove** [TextpressoDevelopers/textpressocentral#34]
Here are the steps to reproduce the bug:

1) Navigate to this WormBase transgene page:

https://wormbase.org/species/all/transgene/WBTransgene00000129#05--10

2) In the References widget, click on the hyperlinked "Textpresso" at the bottom where it reads "Find references identified using Textpresso"

3) On the resulting TPC results page, open Additional Search Options, click the check box for "Sort by Year" and click on "Search!"

4) On the resulting TPC results page, scroll down and click on "Last Page"

5) On the last page of results, try expanding the details for the last paper result

When I perform these steps on Firefox, Chrome, or Safari, TPC automatically reruns the search again without the "Sort by Year" parameter selected. I don't know what might be causing this. Here's a screen recording:

https://www.dropbox.com/s/xzqruby36dxk4nj/TPC_reruns_query_without_prompt_Feb_8_2021.mov?dl=0

**Comment by goldturtle** [comment]
@chris-grove Thanks. I'll look into this.

Michael.

**Comment by goldturtle** [comment]
Fixed @ http://celegans.textpressocentral.org

**Comment by chris-grove** [comment]
@goldturtle 
OK, looks fixed at http://celegans.textpressocentral.org thanks! I guess this fix will make its way to the main TPC site as well?
