### ISSUE TITLE
Selecting a paper to view in the C. elegans site clears the search and results

### ISSUE THREAD

**Issue by vanaukenk** [TextpressoDevelopers/textpressocentral#38]
After a search, I tried to view the results in the context of the full text and when I click on the check box next to a paper entry, the UI says 'loading' and then the search is completely cleared and I'm back to the original search page.

If I'm logged in, I also get logged out.

**Comment by vanaukenk** [comment]
Follow up with @goldturtle 
This bug occurs when performing a document search, but not a sentence search.  
@goldturtle will look into the code to try to fix it.

**Comment by goldturtle** [comment]
Fixed.
