### ISSUE TITLE
celegans.textpressocentral.org/ is down

### ISSUE THREAD

**Issue by chris-grove** [TextpressoDevelopers/textpressocentral#39]

**Comment by chris-grove** [comment]
I cannot get it to load on any browser. Other web sites are loading fine.

**Comment by textpresso** [comment]
Not on my end.

Michael.

**Comment by chris-grove** [comment]
OK I'll close it then. I have no idea why it isn't loading for me; it keeps timing out

**Comment by chris-grove** [comment]
Same issue as #37 
The site times out when I am using Caltech VPN. It would be good to get this sorted out
