### ISSUE TITLE
Migrating from last page to previous page not working

### ISSUE THREAD

**Issue by vanaukenk** [TextpressoDevelopers/textpressocentral#40]
Hi,

If I perform a search on the celegans textpresso site and navigate to the Last page of the search results, I can see the papers listed on the last page, but then clicking on the Previous Page link from the last page doesn't seem to load any of the results.

Thx.

**Comment by goldturtle** [comment]
I can't reproduce the bug and cannot find anything unusual in the log files. What was the query?

**Comment by vanaukenk** [comment]
Thanks @goldturtle 
I just tried my query again ('epidermal') and migrating from the last to previous page seems to be working now.  
If it happens again, I'll reopen the ticket.
