### ISSUE TITLE
C. elegans Textpresso Central seems to be down

### ISSUE THREAD

**Issue by vanaukenk** [TextpressoDevelopers/textpressocentral#41]
Hi,

The C. elegans textpresso site isn't accessible for me this afternoon.

Typing in celegans.textpresso.org takes me to:

http://textpressocentral.org:9000/tpc

which isn't loading anything.

I see the same thing clicking on the link from the Tools menu in WormBase.

**Comment by goldturtle** [comment]
I restarted the instance and it seems to be working now. If I do not 
respond in time, you can ask Valerio to restart it. He know how to.

M.

**Comment by goldturtle** [comment]
I restarted the instance and it seems to be working now. If I do not 
respond in time, you can ask Valerio to restart it. He knows how to.

M.

**Comment by vanaukenk** [comment]
Thank you @goldturtle 
It is working again for me now.
