### ISSUE TITLE
Performing proximity searches

### ISSUE THREAD

**Issue by manulera** [TextpressoDevelopers/textpressocentral#42]
Hello, is it possible to perform proximity searches using Lucene? From the docs of lucene:

> **Proximity Searches**
>Lucene supports finding words are a within a specific distance away. To do a proximity search use the tilde, "~", symbol at the end of a Phrase. For example, to search for "drupal" and "lucene" within 10 words of each other, enter
>"drupal lucene"~10

I don't see how to do this in the S. cerevisiae texpresso for example.

**Comment by textpresso** [comment]
Hello,

unfortunately, this feature is not implemented with Textpressocentral.


Sorry,

Michael.
